Experimental osw
Kev2000-Github/Proyecto_Laboratorio pull request #1
Opened 2022-04-11 23:47 UTC by WolvesDevelopers

Agregando modelo servicio

2022-04-12 00:16 UTC, Kev2000-Github requested changes

2022-04-12 00:16 UTC, Kev2000-Github commented on src/modelos/Servicio.java
> +	private String codigo;
Cambia codigo por id

2022-04-12 02:19 UTC, WolvesDevelopers commented on src/modelos/Servicio.java
> +	private String codigo;
Listo modificacion hecha.

2022-04-12 20:41 UTC, Kev2000-Github requested changes

2022-04-12 20:41 UTC, Kev2000-Github commented on src/modelos/Fundacion.java
> +    private double porcentaje_partido_anual;
en la base de datos se usara snake_case, pero para el codigo por convenio es camelCase

2022-04-12 20:41 UTC, Kev2000-Github commented on src/modelos/Fundacion.java
> +    private double porcentaje_partido_anual;
tambien cambia porcentaje a float, como eso estara limitado entre 0 y 100, entonces no hay necesidad de ser double.
Tambien dudo que el presupuesto llegue a necesitar tanta precision para necesitar double, con float bastaria creo yo

2022-04-12 20:41 UTC, Kev2000-Github commented on src/DAO/FundacionDao.java
> +                    + " FROM fundacion WHERE e.deleted_at IS NULL";
esto te va a dar un error, e no esta declarado en ninguna parte de la query

2022-04-12 20:41 UTC, Kev2000-Github commented on src/DAO/FundacionDao.java
> +            con.execMutation(sql, params);
verifica que esta operacion corra bien, sospecho que va a lanzar error porque presupuesto es float y execMutation lo hice transformando todo en string

2022-04-12 23:22 UTC, Kev2000-Github requested changes

2022-04-12 23:22 UTC, Kev2000-Github commented on src/DAO/FundacionDao.java
> +            fundacion.setPorcentajePartidoAnual(rs.getFloat("porcentajePartidoAnual"));
un problema, lo que esta entre comillas se refiere a como esta el campo dentro de la base de datos, por lo que ahi si iria snake_case, de lo contrario te retornara nulo siempre

2022-04-12 23:22 UTC, Kev2000-Github commented on src/modelos/Fundacion.java
> +        return String.valueOf(porcentajePartidoAnual);
nop, este no  deberia ser la solucion, ya que el getter **siempre** debe retornar el tipo de dato correspondiente al atributo

2022-04-12 23:22 UTC, Kev2000-Github commented on src/modelos/Fundacion.java
> +        return String.valueOf(porcentajePartidoAnual);
en lugar de esto aqui, se deberia hacer dentro del metodo del DAO que lo requiera, aqui estas modificando el funcionamiento en todo el sistema

2022-04-12 23:59 UTC, Kev2000-Github requested changes

2022-04-12 23:59 UTC, Kev2000-Github commented on src/DAO/FundacionDao.java
> +
falta id, hay 4 ?, pero 3 params

2022-04-13 00:28 UTC, Kev2000-Github approved these changes

2022-04-13 00:29 UTC, merged